apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-deployment # Name of the deployment
spec:
  replicas: 1 # Number of desired pods
  selector: # Defines how to identify pods that are managed by this deployment
    matchLabels:
      app: flask-hello
      tier: frontend
  template: # Pod definition template
    metadata:
      labels:
        app: flask-hello
        tier: frontend
    spec:
      containers:
        - name: flask-hello-container
          image: harishdocker557/myapp:latest # Docker image to use
          imagePullPolicy: Always # Always pull image to ensure the latest is used
          # Add ports, environment variables, etc. here as needed
          ports:
            - containerPort: 5000 # Assuming Flask runs on port 5000 by default
