name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the repository code

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Docker build context
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Enables pushing to Docker Hub
        tags: dockerhub/myapp:${{ github.run_number }}  # Tag image with the GitHub Actions run number, replace "dockerhub" with your Docker Hub username

    # Optional: Add additional steps for deployment or testing as needed
