name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  AKS_CLUSTER_NAME: myAKSCluster
  AKS_RESOURCE_GROUP: myAKSResourceGroup
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the repository code

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Docker build context
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Enables pushing to Docker Hub
        tags: harishdocker557/myapp:${{ github.run_number }}  # Tag image with the GitHub Actions run number

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --name ${{ env.AKS_CLUSTER_NAME }} --resource-group ${{ env.AKS_RESOURCE_GROUP }} --file $GITHUB_WORKSPACE/.kube/config --overwrite-existing
      env:
        KUBECONFIG: $GITHUB_WORKSPACE/.kube/config

    # Explicitly set the kubectl context to ensure it's targeting the correct AKS cluster
    - name: Set Kubectl Context
      run: |
        CONTEXT=$(kubectl config current-context)
        echo "Current context is $CONTEXT"
        # Optionally, explicitly set the context if automatic setting fails
        # kubectl config use-context your-aks-cluster-context-name

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml --validate=false # Consider removing --validate=false after ensuring connectivity
        kubectl apply -f service.yaml --validate=false # Consider removing --validate=false after ensuring connectivity
      env:
        KUBECONFIG: $GITHUB_WORKSPACE/.kube/config
        APP_ENV: 'production'  # Example non-credential environment variable
