name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch.

env:
  AKS_CLUSTER_NAME: myAKSCluster
  AKS_RESOURCE_GROUP: myAKSResourceGroup

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Check out the repository code.

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: harishdocker557/myapp:${{ github.run_number }}

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: '${{ secrets.REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}/azure-vote-front:${{ github.sha }}'
          pull-images: false
