name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  AKS_CLUSTER_NAME: myAKSCluster
  AKS_RESOURCE_GROUP: myAKSResourceGroup
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the repository code

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Docker build context
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Enables pushing to Docker Hub
        tags: harishdocker557/myapp:${{ github.run_number }}  # Tag image with the GitHub Actions run number

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --name ${{ env.AKS_CLUSTER_NAME }} --resource-group ${{ env.AKS_RESOURCE_GROUP }} --file $GITHUB_WORKSPACE/.kube/config
      env:
        KUBECONFIG: $GITHUB_WORKSPACE/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      env:
        KUBECONFIG: $GITHUB_WORKSPACE/.kube/config
        APP_ENV: 'production'  # Example non-credential environment variable
